# Generated by Django 5.1.3 on 2024-11-27 11:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AutomobilioModelis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marke', models.CharField(help_text='Įveskite automobilio markę', max_length=100, verbose_name='Markė')),
                ('modelis', models.CharField(help_text='Įveskite automobilio modelį', max_length=100, verbose_name='Modelis')),
            ],
        ),
        migrations.CreateModel(
            name='Paslauga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pavadinimas', models.CharField(help_text='Įveskite paslaugos pavadinimą (pvz., Alyvos keitimas)', max_length=100, verbose_name='Pavadinimas')),
                ('kaina', models.DecimalField(decimal_places=2, help_text='Įveskite paslaugos kainą (pvz., 50.00)', max_digits=10, verbose_name='Kaina')),
            ],
        ),
        migrations.CreateModel(
            name='Automobilis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valst_nr', models.CharField(help_text='Įveskite automobilio valstybinį numerį', max_length=20, verbose_name='Valstybinis numeris')),
                ('vin_kodas', models.CharField(help_text='Įveskite automobilio VIN kodą', max_length=50, verbose_name='VIN kodas')),
                ('klientas', models.CharField(help_text='Įveskite kliento vardą arba pavadinimą', max_length=100, verbose_name='Klientas')),
                ('automobilio_modelis', models.ForeignKey(help_text='Pasirinkite automobilio modelį', null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.automobiliomodelis')),
            ],
        ),
        migrations.CreateModel(
            name='Uzsakymas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unikalus užsakymo ID', primary_key=True, serialize=False)),
                ('data', models.DateTimeField(help_text='Įveskite užsakymo datą', verbose_name='Data')),
                ('automobilis', models.ForeignKey(help_text='Pasirinkite automobilį, kuriam skirtas užsakymas', null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.automobilis')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='UzsakymoEilute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiekis', models.PositiveIntegerField(help_text='Įveskite atliktų paslaugų kiekį', verbose_name='Kiekis')),
                ('paslauga', models.ForeignKey(help_text='Pasirinkite atliktą paslaugą', null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.paslauga')),
                ('uzsakymas', models.ForeignKey(help_text='Pasirinkite užsakymą, kuriam priskirta eilutė', on_delete=django.db.models.deletion.CASCADE, related_name='eilutes', to='autoservice.uzsakymas')),
            ],
        ),
    ]
