# Generated by Django 5.1.3 on 2024-11-27 11:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(help_text='Įveskite automobilio markę', max_length=100, verbose_name='Make')),
                ('model', models.CharField(help_text='Įveskite automobilio modelį', max_length=100, verbose_name='Model')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Įveskite paslaugos pavadinimą (pvz., Alyvos keitimas)', max_length=100, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=2, help_text='Įveskite paslaugos kainą (pvz., 50.00)', max_digits=10, verbose_name='Price')),
            ],
        ),
        migrations.RemoveField(
            model_name='automobilis',
            name='automobilio_modelis',
        ),
        migrations.RemoveField(
            model_name='uzsakymas',
            name='automobilis',
        ),
        migrations.RemoveField(
            model_name='uzsakymoeilute',
            name='paslauga',
        ),
        migrations.RemoveField(
            model_name='uzsakymoeilute',
            name='uzsakymas',
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(help_text='Įveskite automobilio valstybinį numerį', max_length=20, verbose_name='License Plate')),
                ('vin', models.CharField(help_text='Įveskite automobilio VIN kodą', max_length=50, verbose_name='VIN')),
                ('customer', models.CharField(help_text='Įveskite kliento vardą arba pavadinimą', max_length=100, verbose_name='Customer')),
                ('car_model', models.ForeignKey(help_text='Pasirinkite automobilio modelį', null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.carmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unikalus užsakymo ID', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(help_text='Įveskite užsakymo datą', verbose_name='Date')),
                ('car', models.ForeignKey(help_text='Pasirinkite automobilį, kuriam skirtas užsakymas', null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.car')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Įveskite atliktų paslaugų kiekį', verbose_name='Quantity')),
                ('order', models.ForeignKey(help_text='Pasirinkite užsakymą, kuriam priskirta eilutė', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='autoservice.order')),
                ('service', models.ForeignKey(help_text='Pasirinkite atliktą paslaugą', null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.service')),
            ],
        ),
        migrations.DeleteModel(
            name='AutomobilioModelis',
        ),
        migrations.DeleteModel(
            name='Automobilis',
        ),
        migrations.DeleteModel(
            name='Paslauga',
        ),
        migrations.DeleteModel(
            name='Uzsakymas',
        ),
        migrations.DeleteModel(
            name='UzsakymoEilute',
        ),
    ]
