# Generated by Django 5.1.3 on 2024-11-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0002_carmodel_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='customer',
            field=models.CharField(help_text='Įveskite kliento vardą arba pavadinimą', max_length=100, verbose_name='Kleintas'),
        ),
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(help_text='Įveskite automobilio valstybinį numerį', max_length=20, verbose_name='Valstybinis numeris'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin',
            field=models.CharField(help_text='Įveskite automobilio VIN kodą', max_length=50, verbose_name='VIN kodas'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='make',
            field=models.CharField(help_text='Įveskite automobilio markę', max_length=100, verbose_name='Marke'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='model',
            field=models.CharField(help_text='Įveskite automobilio modelį', max_length=100, verbose_name='Modelis'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(help_text='Įveskite užsakymo datą', verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Įveskite atliktų paslaugų kiekį', verbose_name='Kiekis'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text='Įveskite paslaugos pavadinimą (pvz., Alyvos keitimas)', max_length=100, verbose_name='Paslauga'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Įveskite paslaugos kainą (pvz., 50.00)', max_digits=10, verbose_name='Kaina'),
        ),
    ]
