# Generated by Django 5.1.3 on 2024-11-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0003_alter_car_customer_alter_car_license_plate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Automobilis', 'verbose_name_plural': 'Automobiliai'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'AutoModelis', 'verbose_name_plural': 'AutoModeliai'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date'], 'verbose_name': 'Uzsakymas', 'verbose_name_plural': 'Uzsakymai'},
        ),
        migrations.AlterModelOptions(
            name='orderline',
            options={'verbose_name': 'UzsakymoEilute', 'verbose_name_plural': 'UzsakymoEilutes'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Paslauga', 'verbose_name_plural': 'Paslaugos'},
        ),
    ]
