# Generated by Django 5.1.3 on 2024-11-29 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0004_alter_car_options_alter_carmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Naujas'), ('IN_PROGRESS', 'Vykdomas'), ('COMPLETED', 'Užbaigtas'), ('CANCELLED', 'Atšauktas')], default='NEW', help_text='Pasirinkite užsakymo būseną', max_length=20, verbose_name='Statusas'),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(help_text='Pasirinkite užsakymą, kuriam priskirta eilutė', null=True, on_delete=django.db.models.deletion.SET_NULL, to='autoservice.order'),
        ),
    ]
