# Generated by Django 5.1.3 on 2024-12-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0009_order_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, help_text='Įveskite automobilio modelio aprašymą', null=True, verbose_name='Aprašymas'),
        ),
        migrations.AddField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, help_text='Įveskite automobilio modelio aprašymą', null=True, verbose_name='Aprašymas'),
        ),
    ]
