# Generated by Django 5.1.3 on 2024-12-05 10:18

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0010_car_description_order_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='description',
            field=tinymce.models.HTMLField(blank=True, help_text='Įveskite automobilio modelio aprašymą', null=True, verbose_name='Aprašymas'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=tinymce.models.HTMLField(blank=True, help_text='Įveskite automobilio modelio aprašymą', null=True, verbose_name='Aprašymas'),
        ),
    ]
